# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5183398c62c8d9eeb92f1f78c9cb3492c19b78df292f368ae10a1cd6ba84ba53b4d9c7aad4762e1e0ab5bc086a732cf0c59aba11814456599c92b309dc15e397

test:
  secret_key_base: f04d5a3e20f18afa53458484a022c5b3b116e1165881dff0f1d68642f43f8b036cadef4a84812dfceae8babe7d704306d3f4209d34404ec101b6eca37d193600

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
